"""
Django settings for qgisfeedproject project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import logging
import os

logger = logging.getLogger(__name__)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This value is committed and therefore public: anything still using it can
# have its sessions and password reset tokens forged. It is named so that a
# deployment can assert it has been replaced - compare SECRET_KEY against
# INSECURE_DEFAULT_SECRET_KEY in the local settings override.
INSECURE_DEFAULT_SECRET_KEY = "w*x1d0%17@hd6lx8gq#45#8w(w&a-!vupt41%#^ryyxs3l%hz9"
SECRET_KEY = INSECURE_DEFAULT_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
# The default stays True so a plain checkout is usable for development. The
# deployment sets DEBUG=False in the application environment; with debug on,
# any error page exposes the settings and the environment, including secrets.
DEBUG = os.environ.get("DEBUG", "True").strip().lower() in ("1", "true", "yes")

# Public hostname(s), comma separated. DOMAIN_NAME is what the NixOS
# infrastructure passes; QGIS_FEED_PROD_URL is the name the docker compose
# stack uses, kept as a fallback so both paths work unchanged.
#
# An empty result leaves ALLOWED_HOSTS empty, which Django treats as
# "localhost only" while DEBUG is on - more useful for development than the
# [""] this produced before, which rejected every request including localhost.
_domains = os.environ.get("DOMAIN_NAME") or os.environ.get("QGIS_FEED_PROD_URL", "")
ALLOWED_HOSTS = [host.strip() for host in _domains.split(",") if host.strip()]

# Required by Django for any POST over HTTPS behind a TLS-terminating proxy.
# Derived from the same hostnames so a deployment does not have to repeat them.
CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS]
CORS_ORIGIN_WHITELIST = CSRF_TRUSTED_ORIGINS


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    # QGIS Feed applications
    "qgisfeed",
    # Keycloak single sign-on. Deliberately feed-agnostic and namespaced, so
    # that a second QGIS site can reuse it with its own role map.
    "qgis_sso",
    # Dependencies
    "tinymce",  # HTML field
    "imagekit",  # Image crop and resize
    # User visit
    "user_visit",
    # Webpack
    "webpack_loader",
    "mozilla_django_oidc",  # OpenID Connect authentication
]

# Useful debugging extensions
if DEBUG:
    INSTALLED_APPS += [
        "django_extensions",
    ]

SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Re-checks the ID token with Keycloak once it goes stale, so that a
    # revocation there takes effect within OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS
    # rather than whenever the Django session happens to expire. Must come
    # after AuthenticationMiddleware, which is what puts request.user in place.
    "mozilla_django_oidc.middleware.SessionRefresh",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "qgisfeed.middleware.QgisFeedUserVisitMiddleware",
]

ROOT_URLCONF = "qgisfeedproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "templates.context_processors.settings_var",
            ],
        },
    },
]

WSGI_APPLICATION = "qgisfeedproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


def _db(name, legacy, default):
    """Read a database setting, preferring the current name.

    The QGISFEED_DOCKER_* spelling predates the move off docker and is still
    what the compose files pass, so it is accepted as a fallback rather than
    broken.
    """
    return os.getenv(name) or os.getenv(legacy) or default


# Defaults target a local PostgreSQL reached over its unix socket, which is
# how the application is deployed: libpq treats a path as a socket directory,
# and peer or trust authentication then needs no password. The compose files
# pass the docker values explicitly.
DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": _db("DB_NAME", "QGISFEED_DOCKER_DBNAME", "qgisfeed"),
        "USER": _db("DB_USER", "QGISFEED_DOCKER_DBUSER", "qgisfeed"),
        "PASSWORD": _db("DB_PASSWORD", "QGISFEED_DOCKER_DBPASSWORD", ""),
        "HOST": _db("DB_HOST", "QGISFEED_DOCKER_DBHOST", "/var/run/postgresql"),
        "PORT": _db("DB_PORT", "QGISFEED_DOCKER_DBPORT", "5432"),
    }
}

# Local password login is a migration fallback with a bounded life, not a
# standing second front door. One flag gates all three of its effects: the
# ModelBackend below, the password form on the login page, and what Django
# admin's own login view will accept. See docs/sso.md.
LOCAL_LOGIN_ENABLED = os.environ.get("LOCAL_LOGIN_ENABLED", "True").strip().lower() in (
    "1",
    "true",
    "yes",
)

AUTHENTICATION_BACKENDS = ["qgis_sso.auth.QGISOIDCAuthenticationBackend"]
if LOCAL_LOGIN_ENABLED:
    AUTHENTICATION_BACKENDS.append("django.contrib.auth.backends.ModelBackend")


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Destination for collectstatic. Deliberately outside STATICFILES_DIRS, which
# Django refuses to overlap with. The deployment points this at the directory
# the web server serves from.
STATIC_ROOT = os.environ.get("STATIC_ROOT", os.path.join(BASE_DIR, "static_collected"))

# Uploaded files. The default keeps them in the checkout, where the repository
# ships the test fixture images; the deployment points it at persistent storage.
MEDIA_ROOT = os.environ.get("MEDIA_ROOT", os.path.join(BASE_DIR, "media"))
MEDIA_URL = "/media/"

# Directory holding GeoLite2-City.mmdb. MaxMind licensed, so it is not shipped
# with the application and has to be provisioned separately; without it the
# geofence feature resolves no location. The default is the docker image
# layout, so any other deployment sets GEOIP_PATH.
GEOIP_PATH = os.environ.get("GEOIP_PATH", "/var/opt/maxmind/")

# GeoDjango loads libgdal and libgeos with ctypes at import time, and reads
# their locations as Django settings rather than environment variables (see
# django/contrib/gis/gdal/libgdal.py). Under Nix the libraries live in the
# store, where ctypes.util.find_library cannot find them, so the package
# wrappers and the devShell export the paths and they are promoted here.
#
# Left as None when unset, which is what Django expects: it then falls back to
# searching the usual library names, which is correct for the docker images and
# for a system-wide install.
GDAL_LIBRARY_PATH = os.environ.get("GDAL_LIBRARY_PATH")
GEOS_LIBRARY_PATH = os.environ.get("GEOS_LIBRARY_PATH")

# This can be specified in settings_local
MAIN_WEBSITE_URL = "https://qgis.org"

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply")
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = os.environ.get("EMAIL_PORT", 587)
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "noreply")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

try:
    from .settings_local import *
except ImportError:
    pass

LOGIN_REDIRECT_URL = "/manage"
LOGOUT_REDIRECT_URL = "/"


# Webpack
WEBPACK_LOADER = {
    "DEFAULT": {
        "BUNDLE_DIR_NAME": "bundles",
        "STATS_FILE": os.path.join(os.path.dirname(BASE_DIR), "webpack-stats.json"),
    }
}

# Sentry
SENTRY_DSN = os.environ.get("SENTRY_DSN", "")
SENTRY_RATE = os.environ.get("SENTRY_RATE", 1.0)

if SENTRY_DSN and SENTRY_DSN != "":
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        traces_sample_rate=SENTRY_RATE,
    )

# Mastodon
MASTODON_ACCESS_TOKEN = os.environ.get("MASTODON_ACCESS_TOKEN", "")
MASTODON_API_BASE_URL = os.environ.get(
    "MASTODON_API_BASE_URL", "https://mastodon.social"
)

# Bluesky
BLUESKY_HANDLE = os.environ.get("BLUESKY_HANDLE", "")
BLUESKY_PASSWORD = os.environ.get("BLUESKY_PASSWORD", "")

# Telegram
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")

# OpenID Connect authentication
QGIS_AUTH_URL = os.environ.get("QGIS_AUTH_URL", "https://auth.qgis.org")
OIDC_RP_CLIENT_ID = os.environ.get("OIDC_RP_CLIENT_ID", "feed-qgis-org")
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_OP_AUTHORIZATION_ENDPOINT = (
    f"{QGIS_AUTH_URL}/realms/qgis/protocol/openid-connect/auth"
)
OIDC_OP_TOKEN_ENDPOINT = f"{QGIS_AUTH_URL}/realms/qgis/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = f"{QGIS_AUTH_URL}/realms/qgis/protocol/openid-connect/userinfo"
OIDC_OP_JWKS_ENDPOINT = f"{QGIS_AUTH_URL}/realms/qgis/protocol/openid-connect/certs"

# The realm that may issue tokens for this site. Asserted against every ID
# token, because a subject is only unique within its issuer.
SSO_KEYCLOAK_REALM = os.environ.get("SSO_KEYCLOAK_REALM", "qgis")
SSO_ISSUER = f"{QGIS_AUTH_URL}/realms/{SSO_KEYCLOAK_REALM}"

# Where a signed-in user manages their own passkeys and profile.
SSO_ACCOUNT_URL = f"{SSO_ISSUER}/account/"

# Retire the local password the first time an account signs in through
# Keycloak. That sign-in is the proof the account is reachable, so waiting
# longer only keeps a second way in open.
SSO_RETIRE_PASSWORD_ON_LOGIN = os.environ.get(
    "SSO_RETIRE_PASSWORD_ON_LOGIN", "True"
).strip().lower() in ("1", "true", "yes")

# feed-roles is a client scope provisioned on the realm specifically so that
# the client role claim reaches the *userinfo* endpoint. Keycloak's built-in
# 'roles' scope puts resource_access on the access token only, which
# mozilla-django-oidc never reads - a naive integration therefore sees no
# roles at all and everyone logs in with no permissions.
OIDC_RP_SCOPES = "openid email profile feed-roles"

# The client is confidential, so the code exchange cannot complete without
# this. It belongs in settings_local, never in the process environment: the
# deployment's environment is world-readable through the Nix store and
# systemctl show.
#
# settings_local is imported above this point, so read back what it set rather
# than assigning a default over the top of it.
OIDC_RP_CLIENT_SECRET = globals().get("OIDC_RP_CLIENT_SECRET", "")

# Never create a site account from a token. The realm is shared with hub and
# plugins and is LDAP-federatable, so leaving this at its default would grant
# a feed account to every user in the directory. The backend refuses in
# create_user as well; this is the belt to that pair of braces.
OIDC_CREATE_USER = False

OIDC_USE_NONCE = True
# Kept so that RP-initiated logout can pass id_token_hint. Without it, signing
# out of Django leaves the Keycloak session live and the next sign-in
# completes with no prompt, which looks like logout having failed.
OIDC_STORE_ID_TOKEN = True
OIDC_OP_LOGOUT_URL_METHOD = "qgis_sso.auth.provider_logout"

# Where mozilla-django-oidc sends a failed authentication. Almost always a
# realm user with no account here, so the page says so rather than showing a
# traceback.
LOGIN_REDIRECT_URL_FAILURE = "/sso/sign-in-failed/"

# Bound the migration-linking path. Off by default; switched on only for the
# Phase 5 cutover window, during which a token whose username *and* verified
# email both match exactly one unlinked local account binds to it and that
# account's password is made unusable.
SSO_MIGRATION_LINKING = os.environ.get(
    "SSO_MIGRATION_LINKING", "False"
).strip().lower() in ("1", "true", "yes")

# Keycloak client roles, mapped to what they mean on this site. Declarative
# rather than branching code, so a second site supplies its own map without
# touching qgis_sso. Membership is reconciled in full at every sign-in:
# a role removed in Keycloak is removed here.
SSO_ROLE_MAP = {
    "admin": {
        "groups": ["qgisfeedentry_authors", "qgisfeedentry_approver"],
        "is_staff": True,
        "is_superuser": True,
    },
    "web-maintainer": {
        "groups": ["qgisfeedentry_authors", "qgisfeedentry_approver"],
        "is_staff": True,
        "is_superuser": True,
    },
    "reviewer": {
        "groups": ["qgisfeedentry_authors", "qgisfeedentry_approver"],
        "is_staff": True,
        "is_superuser": False,
    },
    "usergroup-author": {
        "groups": ["qgisfeedentry_authors"],
        "is_staff": True,
        "is_superuser": False,
    },
    "author": {
        "groups": ["qgisfeedentry_authors"],
        "is_staff": True,
        "is_superuser": False,
    },
}

# Only these groups are ever added or removed by role mirroring, so a group
# created by hand for an unrelated purpose survives a sign-in.
SSO_MANAGED_GROUPS = ["qgisfeedentry_authors", "qgisfeedentry_approver"]

# --- account provisioning ---------------------------------------------------
# None of this is read by the request path.
SSO_KEYCLOAK_SERVER_URL = QGIS_AUTH_URL
# A dedicated service-account client holding view-users and manage-users. The
# web client must never hold them: a compromise of the site would otherwise be
# a compromise of the realm.
SSO_PROVISIONER_CLIENT_ID = os.environ.get(
    "SSO_PROVISIONER_CLIENT_ID", "feed-qgis-org-provisioner"
)
SSO_PROVISIONER_CLIENT_SECRET = globals().get("SSO_PROVISIONER_CLIENT_SECRET", "")

# Must also be a registered redirect URI on the feed-qgis-org client.
SSO_SETUP_REDIRECT_URI = (
    f"https://{os.environ.get("DOMAIN_NAME", "feed.qgis.org")}/accounts/login/"
)

# 14 days. Keycloak's default of 12 hours is far too short for a migration
# wave; people are on holiday.
SSO_SETUP_LINK_LIFESPAN = 1209600

# Users the admin action will provision in one request. Each costs several
# synchronous calls to Keycloak, and there is no task queue in this project.
SSO_ADMIN_ACTION_MAX_USERS = int(os.environ.get("SSO_ADMIN_ACTION_MAX_USERS", "25"))

# Deep link to a user in the Keycloak admin console. Keycloak's API cannot
# hand back a setup link, so this is the fallback when email does not arrive.
# The console itself lives in the master realm regardless of the target realm.
SSO_KEYCLOAK_CONSOLE_REALM = os.environ.get("SSO_KEYCLOAK_CONSOLE_REALM", "master")
SSO_KEYCLOAK_USER_CONSOLE_URL = (
    f"{QGIS_AUTH_URL}/admin/{SSO_KEYCLOAK_CONSOLE_REALM}/console/"
    f"#/{SSO_KEYCLOAK_REALM}/users/{{sub}}/credentials"
)

# Passkey only. No password is ever set on a provisioned account, so there is
# none to phish or reuse, and no one-time code because a passkey already
# combines something you have with something you are.
SSO_REQUIRED_ACTIONS = ["VERIFY_EMAIL", "webauthn-register-passwordless"]

# Shown on the sign-in failure page when set.
SSO_SUPPORT_URL = os.environ.get("SSO_SUPPORT_URL", "")

# Local settings overrides
# Must be the last!
DJANGO_LOCAL_SETTINGS = os.environ.get(
    "DJANGO_LOCAL_SETTINGS", "settings_local_override.py"
)


def apply_local_settings_override(namespace):
    """Copy every upper-case name from the local override file into namespace.

    DJANGO_LOCAL_SETTINGS may be a bare filename, resolved next to this module,
    or an absolute path - which is how a declarative deployment points at a
    file provisioned outside the source tree.

    Returns True if an override file was found and applied. A settings module
    that assigns values after importing this one can call it again at its end,
    so that the site override keeps the last word.
    """
    try:
        from pathlib import Path

        print(f"Looking for local settings override in {DJANGO_LOCAL_SETTINGS}")

        local_settings_path = Path(__file__).parent / DJANGO_LOCAL_SETTINGS
        if local_settings_path.exists():
            import importlib.util

            spec = importlib.util.spec_from_file_location(
                "settings_local_override", local_settings_path
            )
            settings_local_override = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(settings_local_override)
            for setting in dir(settings_local_override):
                if setting.isupper():
                    namespace[setting] = getattr(settings_local_override, setting)
            print(f"Loaded local settings override from {DJANGO_LOCAL_SETTINGS}")
            return True
        raise ImportError(
            f"Local settings file {DJANGO_LOCAL_SETTINGS} does not exist."
        )
    except ImportError:
        return False


apply_local_settings_override(globals())


# Re-derived after every override has been applied. AUTHENTICATION_BACKENDS is
# computed from LOCAL_LOGIN_ENABLED further up, before settings_local and the
# override file have had their say; without this, a deployment that sets
# LOCAL_LOGIN_ENABLED = False in one of them would hide the password form and
# still happily authenticate against ModelBackend.
#
# Dropping ModelBackend does not drop permission checking. The OIDC backend
# subclasses it, so has_perm() and friends still resolve groups and
# permissions from the database; what goes away is the username-and-password
# authenticate(), which is the part being retired.
AUTHENTICATION_BACKENDS = ["qgis_sso.auth.QGISOIDCAuthenticationBackend"]
if LOCAL_LOGIN_ENABLED:
    AUTHENTICATION_BACKENDS.append("django.contrib.auth.backends.ModelBackend")
